# -*- coding: utf-8 -*-
"""411 numerical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvK3hu_JmN_t7AVhuSU-WBXdkHgEwz2r
"""

import pandas as pd
from datetime import datetime

file_path = "data_with_labels_small.csv"
df = pd.read_csv(file_path)

# Convert timestamp to datetime format (assuming it's in milliseconds)
df["start_time_measurement"] = pd.to_datetime(df["start_time_measurement"], unit='ms')
df["end_time_measurement"] = pd.to_datetime(df["end_time_measurement"], unit='ms')
# Convert scientific notation values to standard float format
df = df.applymap(lambda x: float(x) if isinstance(x, str) and 'e' in x.lower() else x)
# Ensure 'mean_local_disk_space_used' is displayed as a standard decimal format
df["mean_local_disk_space_used"] = df["mean_local_disk_space_used"].apply(lambda x: format(x, 'f'))
df

# Save the processed dataframe to a new CSV file
processed_file_path = "numerical_data_with_labels.csv"
df.to_csv(processed_file_path, index=False)